In [22]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

import warnings
warnings.filterwarnings('ignore')

In [23]:
df = pd.read_csv('Data\Churn_Modelling.csv')
df.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [24]:
## Preprocess the Data --> Dropping Irrelevant Features
df = df.drop(columns=['RowNumber', 'CustomerId', 'Surname'], axis=1)
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France  Female  ...               1        101348.88       1
1          608     Spain  Female  ...               1        112542.58       0
2          502    France  Female  ...               0        113931.57       1
3          699    France  Female  ...               0         93826.63       0
4          850     Spain  Female  ...               1         79084.10       0

[5 rows x 11 columns]

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [26]:
## Encoding 
lb_gender = LabelEncoder()

df['Gender'] = lb_gender.fit_transform(df['Gender'])
df.head()

   CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0          619    France       0  ...               1        101348.88       1
1          608     Spain       0  ...               1        112542.58       0
2          502    France       0  ...               0        113931.57       1
3          699    France       0  ...               0         93826.63       0
4          850     Spain       0  ...               1         79084.10       0

[5 rows x 11 columns]

In [27]:
## OneHotEncoder
from sklearn.preprocessing import OneHotEncoder

onehot_geo = OneHotEncoder(sparse_output=False)
geo_encoded = onehot_geo.fit_transform(df[['Geography']])

geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_geo.get_feature_names_out())
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [28]:
## Combine all the columns with the original Data
df = pd.concat([df.drop(columns=['Geography'], axis=1), geo_encoded_df], axis=1)
df.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [29]:
## Splitting the Data
X = df.drop(columns=['EstimatedSalary'], axis=1)
Y = df['EstimatedSalary']

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
## Saving the Pickle file for Regression

with open('Models\label_regression.pkl', 'wb') as file:
    pickle.dump(lb_gender, file)

with open('Models\onehot_regression.pkl', 'wb') as file:
    pickle.dump(onehot_geo, file)

with open('Models\scaler_regression.pkl', 'wb') as file:
    pickle.dump(scaler, file)

In [32]:
## Training ANN Regression Problem 
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [33]:
model = Sequential([
    Dense(units=64, activation='relu', input_shape = (X_train.shape[1],)),
    Dense(units=32, activation='relu'),
    Dense(units=1)
])

opt = tensorflow.keras.optimizers.Adam()

model.compile(optimizer=opt, loss='mean_absolute_error', metrics=['mae'])

model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [34]:
from tensorflow.keras.callbacks import EarlyStopping

early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

In [35]:
model.fit(
    X_train, y_train, validation_data=(X_test, y_test),
    epochs=100, callbacks= [early_stop]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 100375.3750 - mae: 100375.3750 - val_loss: 98506.6797 - val_mae: 98506.6797
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 99598.9688 - mae: 99598.9688 - val_loss: 96939.9375 - val_mae: 96939.9375
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 96883.0078 - mae: 96883.0078 - val_loss: 92943.6797 - val_mae: 92943.6797
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 91572.0078 - mae: 91572.0078 - val_loss: 86328.5859 - val_mae: 86328.5859
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 83856.3984 - mae: 83856.3984 - val_loss: 77825.4062 - val_mae: 77825.4062
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 74773.3125 - mae: 74773.3125 - val_loss: 68967.3359 - val_mae: 68967.3359
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 66037.9141 - mae: 66037.9141 - val_loss: 61369.9023 - val_mae: 61369.9023
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 59055.3047 - mae: 59055.3047 - val_loss: 55913.7695 - val_mae: 55913.7695
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 54590.4844 - mae: 54590.4844 - val_loss: 52890.4922 - val_mae: 52890.4922
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52195.0664 - mae: 52195.0664 - val_loss: 51516.8555 - val_mae: 51516.8555
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 51064.5156 - mae: 51064.5156 - val_loss: 51041.9922 - val_mae: 51041.9922
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50636.3164 - mae: 50636.3164 - val_loss: 50858.1836 - val_mae: 50858.1836
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50435.9648 - mae: 50435.9648 - val_loss: 50786.2461 - val_mae: 50786.2461
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50314.4414 - mae: 50314.4414 - val_loss: 50737.3125 - val_mae: 50737.3125
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50231.4648 - mae: 50231.4648 - val_loss: 50687.9648 - val_mae: 50687.9648
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50167.0703 - mae: 50167.0703 - val_loss: 50646.9258 - val_mae: 50646.9258
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50109.1836 - mae: 50109.1836 - val_loss: 50615.6914 - val_mae: 50615.6914
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50059.4844 - mae: 50059.4844 - val_loss: 50574.7031 - val_mae: 50574.7031
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50012.9492 - mae: 50012.9492 - val_loss: 50545.1172 - val_mae: 50545.1172
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49973.8008 - mae: 49973.8008 - val_loss: 50515.0586 - val_mae: 50515.0586
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49935.4766 - mae: 49935.4766 - val_loss: 50488.6719 - val_mae: 50488.6719
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49899.7969 - mae: 49899.7969 - val_loss: 50461.7383 - val_mae: 50461.7383
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49872.2930 - mae: 49872.2930 - val_loss: 50440.0156 - val_mae: 50440.0156
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49841.4062 - mae: 49841.4062 - val_loss: 50420.5547 - val_mae: 50420.5547
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49814.8555 - mae: 49814.8555 - val_loss: 50406.4023 - val_mae: 50406.4023
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49790.1680 - mae: 49790.1680 - val_loss: 50397.1094 - val_mae: 50397.1094
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49769.1094 - mae: 49769.1094 - val_loss: 50376.7227 - val_mae: 50376.7227
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49746.0430 - mae: 49746.0430 - val_loss: 50363.4375 - val_mae: 50363.4375
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49726.5898 - mae: 49726.5898 - val_loss: 50355.4414 - val_mae: 50355.4414
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49706.7383 - mae: 49706.7383 - val_loss: 50336.1992 - val_mae: 50336.1992
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49693.6328 - mae: 49693.6328 - val_loss: 50334.2656 - val_mae: 50334.2656
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49671.3516 - mae: 49671.3516 - val_loss: 50323.7695 - val_mae: 50323.7695
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49655.3086 - mae: 49655.3086 - val_loss: 50327.4922 - val_mae: 50327.4922
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49642.0938 - mae: 49642.0938 - val_loss: 50325.5508 - val_mae: 50325.5508
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49626.4258 - mae: 49626.4258 - val_loss: 50308.2891 - val_mae: 50308.2891
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49615.9414 - mae: 49615.9414 - val_loss: 50299.8438 - val_mae: 50299.8438
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49602.5391 - mae: 49602.5391 - val_loss: 50289.5586 - val_mae: 50289.5586
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49592.9062 - mae: 49592.9062 - val_loss: 50294.9688 - val_mae: 50294.9688
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49577.6523 - mae: 49577.6523 - val_loss: 50295.5898 - val_mae: 50295.5898
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49565.9336 - mae: 49565.9336 - val_loss: 50290.6875 - val_mae: 50290.6875
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49557.7539 - mae: 49557.7539 - val_loss: 50292.8945 - val_mae: 50292.8945
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49543.9883 - mae: 49543.9883 - val_loss: 50288.4453 - val_mae: 50288.4453
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49534.8594 - mae: 49534.8594 - val_loss: 50284.6992 - val_mae: 50284.6992
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49524.1484 - mae: 49524.1484 - val_loss: 50278.3945 - val_mae: 50278.3945
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49518.0508 - mae: 49518.0508 - val_loss: 50277.6016 - val_mae: 50277.6016
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49509.8633 - mae: 49509.8633 - val_loss: 50296.4102 - val_mae: 50296.4102
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49498.5391 - mae: 49498.5391 - val_loss: 50287.5391 - val_mae: 50287.5391
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49491.1797 - mae: 49491.1797 - val_loss: 50281.4141 - val_mae: 50281.4141
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49483.3281 - mae: 49483.3281 - val_loss: 50282.7422 - val_mae: 50282.7422
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49476.7891 - mae: 49476.7891 - val_loss: 50281.7148 - val_mae: 50281.7148

In [36]:
loss, metric = model.evaluate(X_test, y_test)
print(f"Test MAE : {metric}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50277.6016 - mae: 50277.6016
Test MAE : 50277.6015625

In [37]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.